name: Deploy Terraform
on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      ref:
        type: string
        default: ''
      runs-on:
        type: string
        default: ubuntu-latest
      skip:
        type: boolean
        default: false
      fail:
        type: boolean
        default: false
      sleep:
        type: number
        default: 0
jobs:
  deploy:
    runs-on: ${{ inputs.runs-on }}
    if: ${{ !inputs.skip }}
    concurrency:
      group: deploy-${{ inputs.environment }}
      queue: max # https://github.com/orgs/community/discussions/12835#discussioncomment-16602100
    steps:
    - name: Deploy script
      run: |
        echo "Running .github/workflows/deploy.yml 🚀"
        echo "environment: ${{ inputs.environment }}"
        if ${{ inputs.fail }}; then
          exit 1
        fi
        echo "Sleeping for ${{ inputs.sleep }}s"
        sleep ${{ inputs.sleep }}
        echo "Done 🟢"
