name: Deploy Terraform
on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      ref:
        type: string
        default: ''
      runs-on:
        type: string
        default: ubuntu-latest
      skip:
        type: boolean
        default: false
      fail:
        type: boolean
        default: false
      sleep:
        type: number
        default: 0
jobs:
  queue:
    runs-on: ${{ inputs.runs-on }}
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v6
    - name: Wait for staging deployment slot
      uses: ./.github/actions/queue-merge-group
      with:
        job-to-wait-for: 'custom-deploy / deploy'
  deploy:
    needs: queue
    if: ${{ !inputs.skip }}
    runs-on: ${{ inputs.runs-on }}
    concurrency: deploy-${{ inputs.environment }}
    steps:
    - name: Deploy script
      run: |
        echo "Running .github/workflows/deploy.yml 🚀"
        echo "environment: ${{ inputs.environment }}"
        if ${{ inputs.fail }}; then
          exit 1
        fi
        echo "Sleeping for ${{ inputs.sleep }}s"
        sleep ${{ inputs.sleep }}
        echo "Done 🟢"
