name: PR Check
on:
  workflow_dispatch:
  pull_request:
    types: [ opened, synchronize, reopened ]
  merge_group:
    types: [ checks_requested ]
permissions:
  id-token: write # configure-aws-credentials
  pull-requests: write # pr comment
jobs:
  pr-checks:
    name: PR checks
    runs-on: ubuntu-latest
    steps:
    - name: Always succeed 🟢
      run: exit 0

  build:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/build.yml

  terraform-checks:
    name: Terraform checks
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'pull_request'
    steps:
    - uses: actions/checkout@v4
    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.10.2
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::097614841487:role/GithubActionsRole
        aws-region: us-east-1
    - name: Terraform validations and plan
      run: |
        terraform init -input=false
        terraform validate
        terraform fmt -check
        terraform plan -input=false -out=tfplan -var 'hash=${{ needs.build.outputs.hash }}'
    - name: Post terraform plan to PR
      uses: borchero/terraform-plan-comment@v2
      with:
        token: ${{ github.token }}
        planfile: tfplan
