name: PR Check
on:
  workflow_dispatch:
  pull_request:
    types: [ opened, synchronize, reopened ]
  merge_group:
    types: [ checks_requested ]
permissions:
  pull-requests: write # pr comment
  id-token: write # configure-aws-credentials
  # contents: read # is this required?
jobs:
  pr-checks:
    name: PR checks
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
    - name: Always succeed 🟢
      run: exit 0

  terraform-checks:
    name: Terraform checks
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
    - uses: actions/checkout@v4
    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.10.2
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::097614841487:role/GithubActionsRole
        aws-region: us-east-1
    - name: Terraform validations and plan
      run: |
        terraform init -input=false
        terraform validate
        terraform fmt -check
        terraform plan -input=false -out=tfplan
    - name: Post terraform plan to PR
      uses: borchero/terraform-plan-comment@v2
      with:
        token: ${{ github.token }}
        planfile: tfplan

  deploy-terraform:
    name: Deploy terraform
    runs-on: ubuntu-latest
    if: github.event_name == 'merge_group'
    concurrency: main
    environment: dev
    outputs:
      success: ${{ steps.sanity.outputs.success }}
    steps:
    - uses: actions/checkout@v4
    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.10.2
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::097614841487:role/GithubActionsRole
        aws-region: us-east-1
    - name: Terraform apply
      run: |
        terraform init -input=false
        terraform apply -auto-approve -input=false
    - name: Fail workflow on deploy error
      if: failure()
      run: echo "Deployment failed, have to rollback 🔴" && exit 1
    - name: Simulate sanity check
      id: sanity
      run: |
        echo "success=true" >> $GITHUB_OUTPUT

  rollback-if-failed:
    name: Rollback & re-apply main
    runs-on: ubuntu-latest
    needs: deploy-terraform
    if: needs.deploy-terraform.outputs.success == 'false'
    concurrency: main
    environment: dev
    steps:
    - uses: actions/checkout@v4
      with:
        ref: main
    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.10.2
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::097614841487:role/GithubActionsRole
        aws-region: us-east-1
    - name: Terraform apply
      run: |
        terraform init -input=false
        terraform apply -input=false -auto-approve
