name: PR Check
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
  merge_group:
    types: [checks_requested]
jobs:
  pr-checks:
    runs-on: ubuntu-latest
    steps:
    - name: Always succeed 🟢
      run: exit 0

  terraform-checks:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write # pr comment
      id-token: write # configure-aws-credentials
      contents: read
    concurrency: main
    environment: dev
    steps:
    - uses: actions/checkout@v4
    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.10.2
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::097614841487:role/GithubActionsRole
        aws-region: us-east-1
    - name: Terraform validations and plan
      run: |
        terraform init -input=false
        terraform validate
        terraform fmt -check
        terraform plan -input=false -out=tfplan
    - name: Post terraform plan to PR
      if: github.event_name == 'pull_request'
      uses: borchero/terraform-plan-comment@v2
      with:
        token: ${{ github.token }}
        planfile: tfplan
    - name: Terraform apply
      if: github.event_name == 'merge_group'
      run: terraform apply -auto-approve -input=false
    - name: Fail workflow on deploy error
      if: failure()
      run: echo "Deployment failed, have to rollback 🔴" && exit 1
